@MyMonolithicApp.Api_HostAddress = https://localhost:7068

GET {{MyMonolithicApp.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@productId = 0b83ed8e-3f57-46aa-3289-08dd26c304bb

### Get all products
GET {{MyMonolithicApp.Api_HostAddress}}/api/products
Accept: application/json

### Get product by ID
GET {{MyMonolithicApp.Api_HostAddress}}/api/products/{{productId}}
Accept: application/json

### Create a new product
POST {{MyMonolithicApp.Api_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "New Product 1",
  "price": 54.98f
}

### Update an existing product
PUT {{MyMonolithicApp.Api_HostAddress}}/api/products/{{productId}}
Content-Type: application/json
Accept: application/json

{
  "id": "0b83ed8e-3f57-46aa-3289-08dd26c304bb",
  "name": "New Product 2",
  "price": 150.0
}

### Delete a product
DELETE {{MyMonolithicApp.Api_HostAddress}}/api/products/{{productId}}
Accept: application/json

GET {{MyMonolithicApp.Api_HostAddress}}/api/products

###
